name: Convert Python to NRO

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: python3 -m pip install pyinstaller

      - name: Convert Python to NRO
        run: pyinstaller --onefile --console hashSwitch.py

      - name: Upload NRO to repository
        uses: actions/upload-artifact@v3
        with:
          name: hashSwitch.nro
          path: dist/hashSwitch.nro
